### ISSUE TITLE
Exception in thread Thread-453

### ISSUE THREAD

**Issue by internoma** [bnlucas/SassBuilder#14]
SassBuilder started.
Exception in thread Thread-453:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 484, in run
  File ".\SassBuilder.py", line 132, in compile_sass
ValueError: zero length field name in format

With the new update, the package has stopped working properly. Can you help me ??

**Comment by bnlucas** [comment]
It seems the Thread call is causing issues on some systems. This has been updated to remove it completely. I was only able to test this on a Windows 8.2 system with Python 2.7 and 3.4. Hopefully this will get it going!

**Comment by internoma** [comment]
If it's something. I have window 7, Python 3.4.3, with sublime text 2.
