### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_sysopen - sass  using sublime text 2 and SassBuilder

### ISSUE THREAD

**Issue by SingularityWatcher** [bnlucas/SassBuilder#22]
Got this error.  Any ideas to solve this pb?  

NB: I have sass working  well from the console anyway: via this command : sass --watch sass:css

/*
Errno::ENOENT: No such file or directory @ rb_sysopen - sass

Backtrace:
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/plugin/compiler.rb:482:in `read'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/plugin/compiler.rb:482:in `update_stylesheet'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/plugin/compiler.rb:215:in `block in update_stylesheets'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/plugin/compiler.rb:209:in `each'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/plugin/compiler.rb:293:in `watch'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/plugin.rb:108:in `method_missing'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/exec/sass_scss.rb:381:in `watch_or_update'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/exec/sass_scss.rb:51:in `process_result'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/exec/base.rb:52:in `parse'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/lib/sass/exec/base.rb:19:in `parse!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sass-3.4.19/bin/sass:13:in `<top (required)>'
C:/Ruby21-x64/bin/sass:23:in `load'
C:/Ruby21-x64/bin/sass:23:in `<main>'
*/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Errno::ENOENT: No such file or directory @ rb_sysopen - sass"; }

**Comment by paizhamdan** [comment]
I have the same problem. I've found a solution to this.

sass --watch css/style.scss:css/style.css (this is the remedy for the error).

Explanation. as you can see i include the main folder which is sass --watch (css) <-- main folder. Then type in what's inside the main folder. Like in my case i have sass --watch css/style.scss So inside my main folder i have style.scss.

As you can see i include my file .scss & .css in one folder. So the next after the semi-colon, it should be sass --watch css/style.scss : css/style.css

Conclusion, include in the folder name and ( / ) forward slash the file inside the folder.
